name: Performance Benchmark

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly
  workflow_dispatch:  # Manual trigger

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      PYTHONPATH: /github/workspace
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'pyproject.toml'
    
    - name: Install dependencies
      run: |
        pip install -e ".[dev]"
        pip install requests tqdm psutil matplotlib
    
    - name: Create directories
      run: |
        mkdir -p benchmark_data benchmark_results reports
    
    - name: Run comprehensive benchmarks
      run: |
        python scripts/automation/auto_benchmark.py --full-suite
    
    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: |
          benchmark_results/
          benchmark_data/
    
    - name: Generate performance report
      run: |
        python scripts/automation/generate_report.py
    
    - name: Upload report to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports
